version: "3"
networks:
  web:
    external: true
services:
  loadeksdi_bot:
    build: .
    networks:
      - web
    expose:
      - "3000"
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.discord-bridge.entrypoints=websecure
      - traefik.http.routers.discord-bridge.rule=Host(`discord-bridge.loadeksdi.com`)
      - traefik.http.routers.discord-bridge.tls=true
      - traefik.http.routers.discord-bridge.tls.certresolver=loadeksdiCertResolver
    restart: "unless-stopped"
